// <auto-generated />
using DB.LondonStockApi.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.LondonStockApi.Web.Migrations
{
    [DbContext(typeof(LondonStockApiContext))]
    partial class LondonStockApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.LondonStockApi.Web.Models.Average", b =>
                {
                    b.Property<string>("TickerSymbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AveragePriceInPounds")
                        .HasColumnType("Money");

                    b.Property<decimal>("TotalSharesExchanged")
                        .HasColumnType("Money");

                    b.HasKey("TickerSymbol");

                    b.ToTable("Averages");
                });

            modelBuilder.Entity("DB.LondonStockApi.Web.Models.Exchange", b =>
                {
                    b.Property<long>("ExchangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExchangeId"));

                    b.Property<string>("BrokerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceInPounds")
                        .HasColumnType("Money");

                    b.Property<decimal>("SharesExchanged")
                        .HasColumnType("Money");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExchangeId");

                    b.ToTable("Exchanges");
                });
#pragma warning restore 612, 618
        }
    }
}
